### PR TITLE
Highlight own username

### LINKED ISSUE #161: Highlight my username in comments to differentiate from other users.

### PR DESCRIPTION
**Pull request by rsammelson**
Fixes #161

### CODE REVIEW

**Comment by rsammelson** [comment]
@aeharding, this PR is ready I think. Can you merge it with a merge commit so that the history of the two separate commits is retained?

**Comment by rsammelson** [comment]
@aeharding This is ready to go again.

**Comment by rsammelson** [comment]
@aeharding What's the status on this?

**Comment by aeharding** [comment]
So a couple concerns:

1. The db item is called `instance_url_mode`, yet the setting is under comments in the UI and only applies to comments. We need a good name for this that describes what this setting actually is for
2. Should this be a global setting? What is the argument for it only applying to comments?

**Comment by rsammelson** [comment]
>     1. The db item is called `instance_url_mode`, yet the setting is under comments in the UI and only applies to comments. We need a good name for this that describes what this setting actually is for

The idea was for the setting to possibly cover more than just comments in the future, but I can rename it to something like `show_instance_url_comment`.

>     2. Should this be a global setting? What is the argument for it only applying to comments?

Do communities not already show their instance?

**Comment by rsammelson** [comment]
Actually, I already applied a change to make this apply to users in the post details, so I should move the setting to a different block.

**Comment by aeharding** [comment]
Sorry, one other question would be should it apply to community handles too? Or should that be its own setting? If its own setting, what would be the use case for that? 🤔

**Comment by aeharding** [comment]
image

Can the setting control these handles too (this is a community page)?

**Comment by rsammelson** [comment]
> Sorry, one other question would be should it apply to community handles too? Or should that be its own setting? If its own setting, what would be the use case for that? 🤔

I think community handles for remote communities should pretty much always show the URL, so I don't think that needs a setting.

Right now this is really an override to force showing instance URLs when they wouldn't be shown. If you want me to add the ability to never show user instance URLs, I can do that in a separate PR.

**Comment by rsammelson** [comment]
One use case would be that if you run your own instance and find a lot of junk coming from users on a specific instance, you could remove it.

**Comment by rsammelson** [comment]
@aeharding alright I finished renaming things and added a general section, so it should hopefully make more sense now.

**Comment by rsammelson** [comment]
> If you want me to add the ability to never show user instance URLs, I can do that in a separate PR.

@aeharding to elaborate on this, I did some cleanup in #185 that I would prefer to have before making any more multi-select settings. Once that is merged I would like to add the ability to turn off instance URLs for people everywhere to simplify the UI for those who want that.

**Comment by aeharding** [comment]
Gotcha, I'll take a look at #185 soon.

**Comment by rsammelson** [comment]
@aeharding, that is blocked on this because they both touched the same preferences code and I didn't want to have merge conflicts, so I would prefer to add that additional feature in a new PR. If I really have to I can rebase that PR onto main instead of this branch, but it will be a little painful.

**Comment by aeharding** [comment]
Oh I misunderstood, so just to confirm you'd prefer this one go first?

**Comment by rsammelson** [comment]
Yes, and once this is merged I'll have two more PRs ready for you shortly.

**Comment by rsammelson** [comment]
@aeharding do you want any other changes here or is this good to go?

**Comment by aeharding** [comment]
I'll check it out soon!

**Comment by aeharding** [comment]
Can you remove the yellow username thing from this PR? We can discuss my concerns in the issue (I commented earlier).

Otherwise LGTM! I just tested and its great.

Maybe we should move this to a "Federation" section below post/comment sections? What do you think about that?

**Comment by aeharding** [comment]
Also I can resolve the conflicts if you'd like, just let me know.

**Comment by rsammelson** [comment]
@aeharding, I fixed the conflicts, but I still have the user highlight; I disabled it on the profile page like I mentioned. If you want it gone altogether let me know.

**Comment by aeharding** [comment]
I think let's pull it out of this PR. There's other concerns too, like light mode contrast, showing in inbox, consistency

**Comment by aeharding** [comment]
Also, the label for the setting is getting cut off on my iPhone. So let's shorten to "Show user instance"

**Comment by rsammelson** [comment]
> showing in inbox, consistency

Can you elaborate on these two? I don't see where your own username shows up in the inbox.

**Comment by rsammelson** [comment]
I also did adjust the color to improve contrast, the contrast still isn't fantastic in light mode, but it is higher than the green used for distinguished usernames.

**Comment by aeharding** [comment]
I am closing this because it has become quite stale. This is something that I may consider in the future as a configurable option, but lets coordinate on the issue if interested.

**Pull request closed without merging**
