### PR TITLE
Add custom icons for time-based sorts

### LINKED ISSUE #197: 🚨 DESIGNER HELP NEEDED: New calendar icons!
Hi there!

Paging all designers that build SVGs!

Apollo had some really nice calendar items for "top" sorts.

This is important, because when sorting by top, the different icon shows in the header of wefwef that allows you to see which "top" sort you have selected.

Example Apollo options:

image

We obviously don't want to exactly copy. Ionic has a nice MIT-licensed calendar SVG we can use as a base:

https://github.com/aeharding/wefwef/assets/2166114/03c8a1df-2563-4786-9333-d2d6d7e38022

Then we just need to style the contents of the calendar item. :)

Here's all of the "top" states in wefwef. We need different icons for each option as SVGs.

### PR DESCRIPTION
**Pull request by tilden**
Fixes #197 -- custom icons for time-based sorts

### CODE REVIEW

**Review by aeharding — APPROVED** [review]
Looks amazing

**Comment by aeharding** [comment]
@tilden, looks like the next release of Ionic will be adding some additional sort options:

image

Would you be able to provide SVGs for these? If so, feel free to make a PR with them and I would be happy to hook them up.

(For controversial, I can probably use an existing Ionic Icon - but if you want/have time to take a swing at that one too, feel free!)

**Comment by tilden** [comment]
Oh nice, glad to see Lemmy is getting a controversial sort option! I can definitely put together some new icon svgs.

Was there a particular Ionic icon you were thinking for Controversial? IIRC Apollo used crossed swords

**Comment by aeharding** [comment]
Yeah, the crossed swords was cool! I was thinking in lieu of a custom design, either using the Ionic skull swap-vertical-outline.

**Comment by tilden** [comment]
I like the skull idea!

Anyway, found some time to put together SVGs for the 3/6/9 month sorts, that follow the same pattern as the clock ones:
calendar-outline-03
calendar-outline-06
calendar-outline-09

**Comment by aeharding** [comment]
Awesome! I created https://github.com/aeharding/voyager/issues/697 to track this. Once 0.19 is deployed to the larger instances these can be added

**Pull request merged**
