### PR TITLE
Share improvements

### LINKED ISSUE #183: Share buttons don't do anything on devices without navigator.share
e.g. desktop computer Firefox

We should probably build our own hook, useShare (or something).

It will accept exact same props as navigator.share.

If navigator.share is undefined, should copy text to clipboard (prefer URL if exists in share payload) and then present toast with useIonToast.

### LINKED ISSUE #255: Sharing posts from a feed shares the images/links, not the post itself
**Disclaimer:** I'm not sure if this is intended or not, since I haven't found any issues/discussions on this topic. The closest thing I could find was #202, which I'm not sure if it solves the matter at hand.

**Wefwef version:** 0.12.0 (installed on mobile)

### The Issue
When I use the **Share** button on a post containing an image/link from any feed - whether it's from a specific community's feed or from the Home/All/Local feeds - the shared URL corresponds to the image/link contained in the post, _not_ the post itself.
When I use the **Share** button on a post with no links or from an individual post's page (with or without images/links), the shared URL corresponds to the post itself, as I would expect.
~I made a video showing the different URLs being generated upon sharing a post with an image, followed by a post with only text - both from my Home feed:~
I *was* going to upload the video, but, for some reason, it's completely black when viewed in Github's preview...
To reproduce, you just have to go to any feed and open the sharing menu on:
- Text posts - which will share the post's URL
- Posts with images/links - which will instead share *their* URLs.

This doesn't happen on an individual post's page, where it always shares the post's URL, regardless of any existing images/links.

https://github.com/aeharding/wefwef/assets/61757466/b28a0fff-d1da-4081-b333-a776d40c7bc8

Since sharing the post itself consequentely grants access to the image/link, it seems to me that this action is more useful than sharing whatever link is contained in the post. Especially since it's possible to share the images/links by tap-holding them, whereas that doesn't seem to be an option for the post itself.

### Possible Solution
I've been looking through the code and eventually found [this line](https://github.com/aeharding/wefwef/blob/6b4758de8d1f252f383950693a3385e91309a5fa/src/features/post/shared/MoreActions.tsx#L196C22-L196C22) that I suspect could be the problem (or, at least, closely related to it). I've noticed from Chrome's network inspector that the `post` objects in the response of a simple text post don't contain a `url` property, so the code on the mentioned line is then relying on the `post.post.ap_id` property (which contains the post's URL), instead of `post.post.url` (which only exists when there is an image/link in the post). I believe sharing the `post.post.ap_id` everytime should be the correct fix, if this issue turns out to be relevant.

screenshot showing lack of URL property on a post object from a text post

 Regardless, since this is the first time I've looked at this app's code and since I've never dabbled in React - let alone React on mobile - it would be better if I let someone else tackle this.

### LINKED ISSUE #474: Add "share image" to image viewer menu
At the moment, you rely on long press on the image in order to share the image itself, not a link to the post.

For parity with Apollo, it would be great if we could get a "Share image" link in the three dots menu when the internal image viewer is open.

### PR DESCRIPTION
**Pull request by rsammelson**
Fixes #183 and adds modal to select what the user would like to share (link to post or link to post content). Fixes #255. Also should fix #474.

share-modal

### CODE REVIEW

**Comment by rsammelson** [comment]
I'm guessing I should move the toast to the bottom. I didn't like how it covered the bottom bar, but now I realize that is a general issue that needs to be solved (#147).

**Comment by rsammelson** [comment]
@aeharding This is back to being ready to merge.

**Comment by rsammelson** [comment]
@aeharding, sorry for the pings, but are you ready for this PR if I fix merge conflicts, or do you want to wait?

**Comment by rsammelson** [comment]
@aeharding I don't think this depends on anything else now, and I have it working with the image gallery share button too.

**Comment by aeharding** [comment]
I'll take a look soon. To be honest, I'm skeptical we need to prompt the user to ask them what they would like to share 🤔 but I will try it out before any really feedback :)

**Comment by aeharding** [comment]
> Oh, I like being able to share content or the post

Was this a feature in Apollo? I know there was the ability to share a picture of the post, but that would be a separate feature.

**Comment by rsammelson** [comment]
I'm not sure, I never used Apollo. I just want to be able to share the post itself with people so they can interact with it (comment/vote). The app I used had a similar feature.

I assume most people aren't sharing often enough to be bothered by a two option popup when they click share, but I could add a setting to always default to sharing the media link if you want. I would really like to get this one merged so I can use it easily.

**Comment by Penagwin** [comment]
Here's a screenshot of the sharing menu from Apollo - I don't remember if anything was below report.

@aeharding Do you want to combine all of the sharing and saving related meta-discussion with #69? There's a several related moving parts with them.

image

**Comment by rsammelson** [comment]
In a future PR, I could add more share options to the modal created here to at least allow non-iOS users to be able to share media directly and also a share as image option. Personally I think it would be a better user experience if they only show up when clicking share, the post actions menu is already very long, and it standardizes the experience between using the share button and post actions (and I can add share as a swipe action with the same component along with customizable swipes).

**Comment by Penagwin** [comment]
What I'm wondering is if we replace the "tap-hold" that iOS 16 users have with just this screen. Then it would be consistent across all platforms?

**Comment by rsammelson** [comment]
Since tap and hold is a often available OS-level thing, I think leaving it is best to match other iOS apps. But I don't feel strongly about that.

**Comment by rsammelson** [comment]
@aeharding I added share as a swipe option and updated from the latest main.

**Comment by aeharding** [comment]
Thanks. I still need time to look at this

**Comment by aeharding** [comment]
Thanks for the PR! I am closing this because it has become quite stale. Additionally, there is now an option to share the post image from the media viewer :)

**Pull request closed without merging**
