### PR TITLE
feat: Distinguish Post Contexts For Blurring Logic

### PR DESCRIPTION
**Pull request by ezfe**
I assume I've violated some project conventions with this PR, so please let me know what your thoughts are and if I should be moving anything around.

This changes the blurring logic from a previously Always/Never option to introduce a third option. Now the user can choose to unblur only within NSFW contexts and default to blurring in Home, Popular, All, and any SFW community.

I was a little unsure on some of the labeling, and the type I added (postContext) I wasn't entirely sure where to drop that.

### CODE REVIEW

**Comment by ezfe** [comment]
@aeharding I've left this as a Draft to represent that while this is fully functional I'm not confident in it's ability to be merged until it's been fully vetted

**Comment by aeharding** [comment]
Hi! This is an interesting idea. So the idea is you would only see NSFW unblurred in feed if you're browsing a NSFW community?

**Comment by ezfe** [comment]
Yup - the context of the post allows the check to be based on the feed the post is in.

If the user is in an NSFW community then the post is unblurred and if the user is in a SFW community or an aggregated feed like Popular then it remains blurred.

**Comment by aeharding** [comment]
@ezfe Is this something you would still like added to Voyager? I noticed that there are quite a few conflicts and it is still marked as a draft.

Btw, I made #1382 to make sure I don't lose track of this.

**Comment by ezfe** [comment]
I feel like it would be a good idea, but I have not been using Voyager recently so take that as you will. I don't have a development environment to resolve the conflicts with at this time unfortunately.

**Comment by aeharding** [comment]
Okay, thanks! I am going to close this for now then, since there is the issue I created to track.

**Pull request closed without merging**
