### PR TITLE
easter egg: detect users from the future

### LINKED ISSUE #914: Need to handle invalid dates
Screenshot_20231109_194920_Chrome

Screenshot_20231109_195030_Chrome

I can work on a PR for this later

> https://github.com/aeharding/voyager/issues/381#issuecomment-1636867004

### PR DESCRIPTION
**Pull request by sharunkumar**
Resolves #914

Related: https://github.com/aeharding/voyager/issues/381#issuecomment-1636867004

image

### CODE REVIEW

**Comment by aeharding** [comment]
Hi, thanks for the PR! I think we should just hide the new account indicator if the account created date is in the future. Otherwise it creates an incentive for people to mess with their DB and break account created dates for other apps

**Comment by sharunkumar** [comment]
But the possibility of abusing this is low as you had mentioned it earlier. Only instance owners have direct access to their DBs.

Either way we already know that this is already being done in the wild, and apps would have to handle this edge case anyway. Which is why I thought it would be a funny easter egg when you come across such a user.

**Comment by aeharding** [comment]
> But the possibility of abusing this is low as you had mentioned it earlier. Only instance owners have direct access to their DBs.

Perhaps, but I still don't want to create any incentive for people to do that :)

It would definitely be a fun easter egg, but in this case, I think it's best to ignore. Thanks again for the PR but I'm closing in favor of #925 :)

**Comment by sharunkumar** [comment]
@aeharding would you consider it if the changes were behind a hidden feature flag (disabled by default) which I could just flip downstream?

**Pull request closed without merging**
