### PR TITLE
Feature: Crossposting

### LINKED ISSUE #84: Add ability to cross-post
It would be really nice to have a button when clicked inside a post to cross post the link to another community.  Maybe next to the upvote, downvote and save buttons?

### PR DESCRIPTION
**Pull request by 0xCmdrKeen**
## Summary

This adds the ability to crosspost existing posts to other communities, for feature parity with Apollo and Lemmy.

There is a new option called "Crosspost to..." in the "more actions" menu for posts, after the "Reply" option. When selected, it presents a community selector to allow the user to chose the community to crosspost to, and then opens the post editor with a copy of the original post, similar to how the Lemmy web client operates. The post body will contain a link to the original post, as well as the markdown-quoted original body (if available).

Icon choice is not necessarily final, [see here](https://github.com/aeharding/voyager/issues/84#issuecomment-1851465842) for possible alternatives.

This fixes #84. Comments and feedback welcome.

## Screenshots

screenshot
screenshot
screenshot
screenshot

## Details

The `PostEditor` and all related components and functions now take two parameters, `post` and `community`, instead of one. Both are optional, but at least one is required. If a community is given but no post, a new post will be created in that community. If a post is given but no community, the post will be edited in-place. If both are given (and are different from each other), a copy of the post will be crossposted to the given community.

### CODE REVIEW

**Comment by aeharding** [comment]
Hi, thanks for the pr! However this is currently assigned to me (#84) because I would like to investigate a more comprehensive approach to cross posting.

Again, please don't work on tasks are already assigned. I will upload a contributing document soon to make this more clear.

**Comment by 0xCmdrKeen** [comment]
Sounds good to me.

**Comment by aeharding** [comment]
Thanks again for the PR. However with the app gaining crosspost support in the next version I am going to be add first class support for crossposts with a separate modal. So I'm closing this PR in anticipation of that!

**Comment by 0xCmdrKeen** [comment]
Okay, no worries! Looking forward to it.

**Pull request closed without merging**
