### PR TITLE
Show icon on deleted comments

### LINKED ISSUE #400: Mark deleted/removed posts more clearly
If a post is deleted, it should be more clearly marked that cannot be faked using markdown.

Currently if a user deletes their own comment it just says _deleted by creator_ in italics. That can be faked by someone easily to make it appear as they deleted their comment when it was in fact their comment. The same applies to removed comments.

My suggestion is to add an icon and/or change the colour of the text to something unique to it being deleted/removed.

Apollo did this for removed posts/threads, although removed posts was a bit more subtle compared to threads. I do not remember how it handed user deleted posts though.

image

### PR DESCRIPTION
**Pull request by rsammelson**
Prevents forging deletion with markdown. Fixes #400.

<br />

<br />
<br />

<details>
  <summary>Old look</summary>
  
  <br />
  
</details>

### CODE REVIEW

**Comment by kerosyn** [comment]
Just my 2 cents, it might be better to add the icon to the “deleted by creator” and “removed by mod”. Having it next to the username could be interpreted as the user was deleted.

Especially if a banned icon/flair were to be added to the user as kinda referred to in issue #476, though that issue is currently only talking about the user profile.

Also if new/old account indicators are added (#17 and #381), it could make it look too busy. Especially with long usernames or user instances.

**Comment by rsammelson** [comment]
I agree with you, I'll update soon

**Review by sharunkumar — APPROVED** [review]
Rebase was straightforward, seems like this can be updated to the latest version after resolving minor conflicts

**Comment by rsammelson** [comment]
@aeharding should I update this?

**Comment by aeharding** [comment]
If you'd like - but I am working on comment moderation in #512 so there will be some conflicts there.

**Comment by aeharding** [comment]
Thanks for your patience :) Finally got this in with the mod stuff done.

**Pull request merged**
