### PR TITLE
feat: added action sheet and direct link to profile in chat page

### PR DESCRIPTION
**Pull request by sharunkumar**
image

### CODE REVIEW

**Comment by aeharding** [comment]
Hi thanks!

Can we put this in a menu like we do in other places? See apollo example below. You can copy `SpecialFeedMoreActions.tsx` if you merge main.

IMG_3193

**Comment by sharunkumar** [comment]
> Can we put this in a menu like we do in other places?

Hey, so currently, the top corner button is for "mark all as read". so if I do this, should that also be moved to the menu?

**Comment by sharunkumar** [comment]
@aeharding its done now :+1: 

image

**Comment by aeharding** [comment]
Looks great!

**Pull request merged**
