### PR TITLE
feat: cake day 🍰

### PR DESCRIPTION
**Pull request by sharunkumar**
addresses #59

### CODE REVIEW

**Comment by aeharding** [comment]
Thanks for the PR! I'll check it out shortly

**Comment by sharunkumar** [comment]
@aeharding so with the current patch, people who have just created an account < 24h also shows as cake day. is this the way its supposed to work?

**Comment by rsammelson** [comment]
Will this show the icon at different times for people in different time zones?

**Comment by sharunkumar** [comment]
> Will this show the icon at different times for people in different time zones?

time is not taken into account when comparing today's date and the published date. so I think it shouldn't be an issue, since both dates are converted to local time? :thinking:

**Comment by aeharding** [comment]
Logic should now take everything into account - and also not show cake day for brand new users. :)

I added some tests too in case more edge cases come up!

**Pull request merged**
