### PR TITLE
Add option to unblur NSFW images/videos

### PR DESCRIPTION
**Pull request by NoXmawe**
Implement #70 - Adds a setting to the appearances menu to decide whether or not you want nsfw images blurred. Defaults to blurred. Not super familiar with react but thought i'd give this a try :)

### CODE REVIEW

**Comment by burakcan** [comment]
I think this setting should be per handle. It's probably common to have 2 separate accounts where in one you'd want the nsfw images blurred.

**Comment by NoXmawe** [comment]
I considered that, but I had no idea how to do it. I'll look into it.

**Comment by rsammelson** [comment]
@NoXmawe It will be possible with #246

**Comment by aeharding** [comment]
@NoXmawe Now that we have #246 in this can be merged. Are you interested in updating the branch and incorporating that? Otherwise we can start fresh.

**Comment by aeharding** [comment]
Closing in favor of #427 :)

**Pull request closed without merging**
