### PR TITLE
feat: Manage instances list

### LINKED ISSUE #116: Custom server viewing when anonymous

### PR DESCRIPTION
**Pull request by 0xCmdrKeen**
Took a stab at #998. 

This adds a "Manage instances" screen to the Settings menu which allows editing the default list of Lemmy instances used by the app. Instances can be added and deleted, reordering is currently not implemented. There is a button to restore the default list in case the user messes up.

Newly added instances are verified to be Lemmy servers (using the `getSite()` call) before being added to the list. The list is stored in the database to make it persistent.

The Login and LoggedOut screens will now use the custom server list (this fixes #116). When choosing the "Other" option on the Login screen, if the login was successful, the instance will be added to the list automatically. 

As I mentioned in the issue discussion, I'm not entirely decided whether the "Manage instances" setting should be a top-level item or go into one of the existing categories, but of course this can be changed before merging. 

I'm also happy to change the particulars about where in the Redux state and the database the list is stored.

### CODE REVIEW

**Comment by 0xCmdrKeen** [comment]
Just noticed the part in the project README about self-hosting and using a custom server list, and finally understood the remaining code in `services/app.ts` that I couldn't quite figure out before.

Obviously, this feature will likely not be desirable in that scenario. Will figure out a way to disable it. And easy solution would be to only have it enabled in the native app, since that doesn't use an external server list anyways, but it would also prevent it from showing up in the development preview version or on general purpose deployments like vger.app. But I'll think of something.

**Comment by aeharding** [comment]
Thanks for the PR. This one is a bit involved just because the custom servers logic has a lot of edge cases depending on the users' platform, self-hosted config etc so that is why I haven't gotten to reviewing yet.

**Comment by 0xCmdrKeen** [comment]
@aeharding agreed, and as you may have noticed, I already found some of those edge cases myself :)

But yes, this is certainly a more complex feature and I understand that it requires a thorough review to make sure it doesn't unintentionally break anything.

**Comment by aeharding** [comment]
Hi @0xCmdrKeen thanks again for you PR and effort on this!

I think this PR fits better with Voyager's old login flow. However this is definitely something I would like to add, in some form or another.

With Voyager's new log in flow being an autocomplete list, I think it would be cool if instances could be remembered for next time. Essentially a "recently logged in" list, or something of that nature.

That's a bit of an easier user experience, and would be helpful for people that don't want to take the time to configure a list of custom instances in Settings.

So that's why I'm closing this PR. But again I do want to address #998.

I'm hoping to get a PR out this weekend that will allow browsing and switching between anonymous (logged out) instances. Once that gets merged, I'd be happy to accept a PR with some form of autocomplete/remembering recently logged in instances. We can discuss more on #998, if you'd like.

**Pull request closed without merging**
