### PR TITLE
feat: present account switcher on long pressing profile button in navbar

### PR DESCRIPTION
**Pull request by rahulakrishna**
https://github.com/aeharding/wefwef/assets/10240002/6e976c17-cca5-4131-b74b-17a51a83857c

- add react-hammer.js
- present account switcher `onPress`

resolves: https://github.com/aeharding/wefwef/issues/85

### CODE REVIEW

**Comment by rahulakrishna** [comment]
I need to push one more thing before this thing can be reviewed

**Comment by rahulakrishna** [comment]
this can be reviewed now

**Comment by aeharding** [comment]
Thanks for the PR. However the logic is too glitchy for this to be merged. There's more refactor needed to get this working well unfortunately, particularly to ActorRedirect

**Comment by rahulakrishna** [comment]
Thanks for pointing me to ActorRedirect!

https://github.com/aeharding/voyager/assets/10240002/09e95149-029d-44b6-9f38-869fee344758

I've moved the redirect logic to ActorRedirect and removed the `onSuccess` callback

**Comment by aeharding** [comment]
@rahulakrishna, thanks for looking into that. I'm still seeing some odd behaviors, for example when you try to swipe back after switching accounts, or sometimes where tapping an account doesn't switch the first time.

Also, check out #390 from @zackhow - it seems to be very similar - perhaps you at @zackhow can collab on this?

**Comment by rahulakrishna** [comment]
@zackhow @aeharding
https://greasyfork.org/en/scripts/469273-lemmy-universal-link-switcher

these guys have clearly solved the issue of cross-instance posts. I'll see if I can port their logic to our app

**Comment by aeharding** [comment]
Thanks for this PR @rahulakrishna! I'm closing for now due to the outstanding issue above regarding animation/transition glitches. Feel free to make a new PR if you find a good solution for that!

**Pull request closed without merging**
