### PR TITLE
ci: add helm chart

### PR DESCRIPTION
**Pull request by tibuntu**
Hi there!

I really love the project and really wanted to contribute.

This PR will add a Helm-Chart that can be used to self-host Voyager via Kubernetes.

Since you provided an example of self-hosting Voyager via Docker, I thought people might be interested to self-host via Kubernetes, too.

I have deployed the chart successfully to my local k3s cluster. It also contains the possibility to set the `CUSTOM_LEMMY_SERVERS` environment variable if wanted.

Last but not least I added another Github workflow to enable hosting the chart via Github pages but I'm rather unfamiliar with it so maybe take a look at the docs of the workflow and decide by your own:  https://github.com/marketplace/actions/helm-chart-releaser

If the chart won't be published, one needs to install the helm-chart after cloning the repo (See `README.md`)

Looking forward for feedback!

### CODE REVIEW

**Comment by aeharding** [comment]
Hi! Thanks for the PR!

I'm actually not familiar with Kubernetes at all. If anyone here is familiar, I'd really appreciate a code review!

**Comment by Penagwin** [comment]
@aeharding 
I have nothing against kubernetes, but if we add this can we also add a docker-compose.yml setup for this? I can make a PR for it.

docker-compose is a lot simpler for this type of application where most users don't need the full tooling of k8's

**Comment by ip025** [comment]
> Hi! Thanks for the PR!
> 
> I'm actually not familiar with Kubernetes at all. If anyone here is familiar, I'd really appreciate a code review!

The helm chart portion of the PR looks good to me.

**Comment by tibuntu** [comment]
I have published the Helm-Chart by myself now. So if anyone is interested in using it, visit either the related [Github page](https://tibuntu.github.io/helm-charts/) or view all releases von [ArtifactHub](https://artifacthub.io/packages/helm/tibuntu/voyager)

**Comment by aeharding** [comment]
@tibuntu Hey, that's pretty cool! Would you be interested in adding a link to that from Voyager's readme as an unofficial distribution? This would be best, again I'm hesitant to merge this as officially supported since I have no way to support it 😅

If so, feel free to make another PR and we can close this one.

**Comment by aeharding** [comment]
I'm closing this, but feel free to make a PR with a readme link your helm chart!

**Pull request closed without merging**
