### PR TITLE
Add in-app purchases for tips

### PR DESCRIPTION
**Pull request by aeharding**

### CODE REVIEW

**Comment by SrivatsanSenthilkumar** [comment]
Out of curiosity, will apple/google receive a cut of this donation. If yes, could you put a message that people can pay using github or librepay so more of the money people are tipping/donating reaches your hands. This is a great idea though and thunderbird got a great amount of donations by having in app tips/donations messages(which were out of the way and not annoying popups) and option to tip/donate in app as well

**Comment by aeharding** [comment]
> If yes, could you put a message that people can pay using github or librepay so more of the money people are tipping/donating reaches your hands. 

unfortunately, I don’t think the App Store allows advertising paying externally :/ they want their 15%

**Comment by SrivatsanSenthilkumar** [comment]
> > If yes, could you put a message that people can pay using github or librepay so more of the money people are tipping/donating reaches your hands. 
> 
> unfortunately, I don’t think the App Store allows advertising paying externally :/ they want their 15%

Wasn't there some law passed after the apple/Google vs epic case where it was mandated that apple and Google have to allow 3rd payment portals for in app purchases.

**Comment by aeharding** [comment]
I don't think so. At least, not yet?

image

**Comment by SrivatsanSenthilkumar** [comment]
> I don't think so. At least, not yet?
> 
> image
> 

Sadge. At least the pwa and f-droid builds can like the GitHub. Hopefully this will get more people to donate and reward you for all the hard work

**Pull request merged**
